# Generated by Django 3.2.5 on 2021-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('year_of_production', models.SmallIntegerField(blank=True, default=2000)),
                ('fuel_type', models.CharField(blank=True, max_length=10, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=8, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
